// website/lib/quote/catalog.ts

export interface CatalogProduct {
  id: string
  category: string
  categorySlug: string
  name: string
  description: string
  priceFrom: string
  image: string
  hasCustomSize: boolean
}

export const LAUNDRY_FREQUENCY_OPTIONS = [
  { value: 'daily', label: 'Daily' },
  { value: 'every-2-days', label: 'Every 2 days' },
  { value: 'every-3-days', label: 'Every 3 days' },
  { value: 'weekly', label: 'Weekly' },
  { value: 'custom', label: 'Other (describe in notes)' },
]

export const PRODUCT_CATEGORIES = [
  'Bath Towels',
  'Bed Linen',
  'Bedding',
  'F&B Linen',
  'Bathrobes',
  'Slippers',
  'Kitchen & Sanitation',
] as const

export const CATALOG: CatalogProduct[] = [
  // Bath Towels
  {
    id: 'towel-face',
    category: 'Bath Towels',
    categorySlug: 'towels',
    name: 'Face Towel',
    description: '30×30cm. 400–600 GSM Egyptian cotton. Available in white, ivory, and sand.',
    priceFrom: 'From USD $0.95 / unit',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'towel-hand',
    category: 'Bath Towels',
    categorySlug: 'towels',
    name: 'Hand Towel',
    description: '50×90cm. 400–600 GSM Egyptian cotton. Hemstitched or plain border.',
    priceFrom: 'From USD $1.80 / unit',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'towel-bath',
    category: 'Bath Towels',
    categorySlug: 'towels',
    name: 'Bath Towel',
    description: '70×140cm. 500–700 GSM Egyptian cotton. Most popular hotel standard.',
    priceFrom: 'From USD $4.50 / unit',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'towel-bath-sheet',
    category: 'Bath Towels',
    categorySlug: 'towels',
    name: 'Bath Sheet',
    description: '90×150cm. 600–900 GSM. Luxury oversized format for suites and spas.',
    priceFrom: 'From USD $7.20 / unit',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'towel-pool',
    category: 'Bath Towels',
    categorySlug: 'towels',
    name: 'Pool / Beach Towel',
    description: '90×180cm. 400–500 GSM. Lightweight, quick-dry, stripe patterns available.',
    priceFrom: 'From USD $5.50 / unit',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'towel-gym',
    category: 'Bath Towels',
    categorySlug: 'towels',
    name: 'Gym / Sport Towel',
    description: '40×80cm. 400 GSM. Compact, absorbent, suitable for fitness centres.',
    priceFrom: 'From USD $2.20 / unit',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  // Bed Linen
  {
    id: 'linen-single-sheet',
    category: 'Bed Linen',
    categorySlug: 'bed-linen',
    name: 'Single Flat Sheet',
    description: '160×260cm. 200–500 TC Egyptian cotton or poly-cotton blend.',
    priceFrom: 'From USD $13.04 / sheet',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'linen-double-sheet',
    category: 'Bed Linen',
    categorySlug: 'bed-linen',
    name: 'Double / Queen Flat Sheet',
    description: '230×260cm. 200–500 TC. White, ivory, or custom colour.',
    priceFrom: 'From USD $18.50 / sheet',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'linen-king-sheet',
    category: 'Bed Linen',
    categorySlug: 'bed-linen',
    name: 'King Flat Sheet',
    description: '270×290cm. 200–500 TC. Satin stripe or plain weave.',
    priceFrom: 'From USD $22.00 / sheet',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'linen-pillowcase',
    category: 'Bed Linen',
    categorySlug: 'bed-linen',
    name: 'Pillowcase',
    description: '50×75cm standard. 200–400 TC. Oxford or housewife style.',
    priceFrom: 'From USD $4.80 / pair',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'linen-duvet-cover',
    category: 'Bed Linen',
    categorySlug: 'bed-linen',
    name: 'Duvet Cover',
    description: 'Single to Super King. 300–500 TC. Button or zip closure.',
    priceFrom: 'From USD $24.00 / cover',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  // Bedding
  {
    id: 'bedding-pillow',
    category: 'Bedding',
    categorySlug: 'bedding',
    name: 'Pillow Insert',
    description: '50×75cm. Microfiber hollow-fibre fill. Hypoallergenic. Medium or firm.',
    priceFrom: 'From USD $5.50 / pillow',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'bedding-duvet',
    category: 'Bedding',
    categorySlug: 'bedding',
    name: 'Duvet Insert',
    description: 'Single to Super King. 150–300 GSM. Lightweight fill for warm climates.',
    priceFrom: 'From USD $18.00 / duvet',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'bedding-mattress-protector',
    category: 'Bedding',
    categorySlug: 'bedding',
    name: 'Mattress Protector',
    description: 'Single to Super King. Waterproof, breathable, fitted or flat.',
    priceFrom: 'From USD $2.00 / protector',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'bedding-mattress-topper',
    category: 'Bedding',
    categorySlug: 'bedding',
    name: 'Mattress Topper',
    description: 'Single to Super King. 500–1000 GSM microfiber. Adds luxury to standard mattresses.',
    priceFrom: 'From USD $28.00 / topper',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'bedding-cushion',
    category: 'Bedding',
    categorySlug: 'bedding',
    name: 'Decorative Cushion',
    description: '45×45cm or 60×60cm. Poly-cotton cover, microfiber fill. Custom colours.',
    priceFrom: 'From USD $6.50 / cushion',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  // F&B Linen
  {
    id: 'fb-tablecloth',
    category: 'F&B Linen',
    categorySlug: 'fb-linen',
    name: 'Tablecloth',
    description: '100% cotton or poly-cotton. Round, square, rectangular. Custom sizing.',
    priceFrom: 'From USD $8.50 / cloth',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'fb-napkin',
    category: 'F&B Linen',
    categorySlug: 'fb-linen',
    name: 'Dinner Napkin',
    description: '45×45cm. 200–300 GSM cotton. White or ivory. Logo embroidery available.',
    priceFrom: 'From USD $1.50 / napkin',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  {
    id: 'fb-chair-cover',
    category: 'F&B Linen',
    categorySlug: 'fb-linen',
    name: 'Chair Cover',
    description: 'Banquet chair cover. Poly-cotton or lycra stretch. Multiple colours.',
    priceFrom: 'From USD $3.20 / cover',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'fb-table-runner',
    category: 'F&B Linen',
    categorySlug: 'fb-linen',
    name: 'Table Runner',
    description: '30×180cm. 100% cotton. Adds style to banquet or fine dining setups.',
    priceFrom: 'From USD $4.00 / runner',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: true,
  },
  // Bathrobes
  {
    id: 'robe-terry',
    category: 'Bathrobes',
    categorySlug: 'bathrobes',
    name: 'Terry Bathrobe',
    description: 'M–XXL. 380 GSM looped terry. Heavy, plush, classic luxury feel.',
    priceFrom: 'From USD $21.00 / robe',
    image: 'https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'robe-waffle',
    category: 'Bathrobes',
    categorySlug: 'bathrobes',
    name: 'Waffle Bathrobe',
    description: 'M–XXL. 280 GSM waffle weave. Lightweight — ideal for Zanzibar climate.',
    priceFrom: 'From USD $18.50 / robe',
    image: 'https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'robe-velour',
    category: 'Bathrobes',
    categorySlug: 'bathrobes',
    name: 'Velour Bathrobe',
    description: 'M–XXL. 350 GSM velour. Soft outer finish, terry inner. Premium look.',
    priceFrom: 'From USD $24.00 / robe',
    image: 'https://images.unsplash.com/photo-1600011689032-8b628b8a8747?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  // Slippers
  {
    id: 'slipper-terry',
    category: 'Slippers',
    categorySlug: 'slippers',
    name: 'Terry Slipper',
    description: 'OSFA. Terry upper, EVA non-slip sole. Open or closed toe.',
    priceFrom: 'From USD $1.10 / pair',
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'slipper-waffle',
    category: 'Slippers',
    categorySlug: 'slippers',
    name: 'Waffle Slipper',
    description: 'OSFA. Waffle upper, soft insole. Lightweight and breathable.',
    priceFrom: 'From USD $1.40 / pair',
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'slipper-velour',
    category: 'Slippers',
    categorySlug: 'slippers',
    name: 'Velour Slipper',
    description: 'OSFA. Velour upper, EVA sole. Premium presentation for luxury properties.',
    priceFrom: 'From USD $1.90 / pair',
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  // Kitchen & Sanitation
  {
    id: 'kitchen-towel',
    category: 'Kitchen & Sanitation',
    categorySlug: 'kitchen-sanitation',
    name: 'Kitchen Towel',
    description: '40×60cm. Cotton or linen. Sold per dozen. High-absorbency for food service.',
    priceFrom: 'From USD $6.00 / dozen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'kitchen-glass-cloth',
    category: 'Kitchen & Sanitation',
    categorySlug: 'kitchen-sanitation',
    name: 'Glass Cloth',
    description: '50×70cm. Lint-free. Sold per dozen. Essential for bar and fine dining.',
    priceFrom: 'From USD $8.00 / dozen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'kitchen-chef-towel',
    category: 'Kitchen & Sanitation',
    categorySlug: 'kitchen-sanitation',
    name: 'Chef Towel',
    description: '35×65cm. Heavy cotton twill. Sold per dozen. Loop for apron attachment.',
    priceFrom: 'From USD $9.00 / dozen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
  {
    id: 'kitchen-microfiber-duster',
    category: 'Kitchen & Sanitation',
    categorySlug: 'kitchen-sanitation',
    name: 'Microfiber Duster',
    description: '30×40cm. 280 GSM microfiber. Sold per dozen. Housekeeping standard.',
    priceFrom: 'From USD $7.50 / dozen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=70&auto=format&fit=crop',
    hasCustomSize: false,
  },
]
